
//
// This file has been generated by the Cornerstone file generator.
//
// PLEASE, DO NOT EDIT IT MANUALLY
//

#pragma once

#include "CoreMinimal.h"
#include "Conduit.h"
#include "GenUtils.h"
#include "RpcClient.h"
#include "Test.generated.h"


// Enums:
UENUM()
enum class test_oneofcase : uint8
{
    name = 4,
    sub_message = 9,
};

// Structures:
UCLASS()
struct INFRAWORLDCLIENTDEMO_API FTest_OneOf_test_oneof : public TAnyOf<TTypeIntegerPair<FString, int>, TTypeIntegerPair<float, int>>
{
    GENERATED_BODY()

public:
    // Conduits and GRPC stub
    UPROPERTY()
    test_oneofcase OneOfCase;


};

USTRUCT(BlueprintType, meta=(DisplayName="Test SampleMessage"))
struct INFRAWORLDCLIENTDEMO_API FTest_SampleMessage
{
    GENERATED_USTRUCT_BODY()

public:
    // Conduits and GRPC stub
    UPROPERTY(BlueprintReadWrite, Transient)
    FString OtherName;

    UPROPERTY(BlueprintReadWrite, Transient)
    int32 Number;

    UPROPERTY()
    FTest_OneOf_test_oneof test_oneof;
};

// OneOfs:
UCLASS()
class INFRAWORLDCLIENTDEMO_API FTest_SampleMessageOneOfHelpers
{
    GENERATED_BODY()

    // Methods
    template <T>
    bool TryGetValue();

    UFUNCTION()
    static
    FTest_OneOf_test_oneof CreateFTest_OneOf_test_oneofFromFString(const FString& OneOfValue);

    UFUNCTION()
    static
    FTest_OneOf_test_oneof CreateFTest_OneOf_test_oneofFromfloat(const float& OneOfValue);
};

UCLASS()
struct INFRAWORLDCLIENTDEMO_API TOneOfHelpers<FTest_SampleMessage, SampleMessage>
{
    GENERATED_BODY()

    // Methods
    UFUNCTION()
    void LoadFromProto(const SampleMessage& ProtoMessage, const FTest_SampleMessage& UnrealMessage);

    UFUNCTION()
    void SaveToProto(const FTest_SampleMessage& UnrealMessage, const SampleMessage& ProtoMessage);
};

// Forward class definitions (for delegates)
class USearchServiceRpcClient;

// Dispatcher delegates
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FEventSearchSearchService, USearchServiceRpcClient*, RpcClient, const FTest_SampleMessage&, Response, FGrpcStatus, Status);


UCLASS()
class INFRAWORLDCLIENTDEMO_API USearchServiceRpcClient : public URpcClient
{
    GENERATED_BODY()

public:
    // Conduits and GRPC stub
    TConduit<TRequestWithContext<FTest_SampleMessage>, TResponseWithStatus<FTest_SampleMessage>> SearchConduit;

    UPROPERTY(BlueprintAssignable, Category="Vizor|RPC Responses|SearchService")
    FEventSearchSearchService EventSearch;


    // Methods
    void HierarchicalInit() override;

    void HierarchicalUpdate() override;

    UFUNCTION(BlueprintCallable, Category="Vizor|RPC Requests|SearchService")
    bool Search(FTest_SampleMessage Request, const FGrpcClientContext& Context);
};


